Repository capstone-O-trio/math-helper-front, pull requests merged in 2025-10, with the labels that each got.

#5 [feat/#3] 손 랜드마크 인식
  public/사과.png
  src/App.tsx
  src/components/HandTracker.tsx
Labels: 🚀 Feat, ☘️ 연우

#6 [Feat/#4] 손 상태 및 위치 파악
  src/components/HandTracker.tsx
  src/utils/handState.ts
Labels: 🚀 Feat, ☘️ 연우

#8 [feat#1] 스타일/파일 구조/라우팅 세팅
  .vscode/settings.json
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/font/subset-PretendardVariable.woff
  public/font/subset-PretendardVariable.woff2
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.tsx
  src/components/Button/Botton.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/HandTrackingPage.tsx
  src/pages/OnboardingPage.tsx
  src/router/Router.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: 🤤 보운, 🚀 Feat

#13 [Design#9] ui 퍼블리싱
  src/App.tsx
  src/components/common/Button.tsx
  src/components/common/Heading.tsx
  src/components/common/Input.tsx
  src/components/common/Text.tsx
  src/components/common/TextButton.tsx
  src/pages/LoginPage.tsx
  src/pages/OnboardingPage.tsx
  src/pages/SignupPage.tsx
  src/pages/UploadPage.tsx
  src/router/Router.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: 🤤 보운, 🚀 Feat, 🫟 Design
